<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="[7.1.0]" />
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.6.2" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.2.1" />
    <PackageReference Include="TUnit.Core" Version="0.57.1" />
    <PackageReference Include="TUnit.Engine" Version="0.57.1" />
  </ItemGroup>

  <ItemGroup>
    <!-- Copy defs and patches folder to output. -->
    <Content Include="Defs\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Patches\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <!-- Ignore test results -->
    <Compile Remove="TestResults\**" />
    <EmbeddedResource Remove="TestResults\**" />
    <None Remove="TestResults\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Define.SourceGen\Define.SourceGen.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestSharedLib\TestSharedLib.csproj"/>
  </ItemGroup>
  
</Project>
