<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Engine" />
  </ItemGroup>
  
  <ItemGroup>
    <!-- Copy defs and patches folder to output. -->
    <Content Include="Content\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Define.Zip\Define.Zip.csproj" />
    <ProjectReference Include="..\TestSharedLib\TestSharedLib.csproj" />
  </ItemGroup>

</Project>
