<Project>
  <ItemGroup>
    <PackageVersion Include="Ceras" Version="4.1.7" />
    <PackageVersion Include="FluentAssertions" Version="7.1.0" />
    <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageVersion Include="Microsoft.CodeAnalysis" Version="4.11.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Common" Version="4.11.0" />
    <PackageVersion Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.6.2" />
    <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport" Version="2.2.1" />
    <PackageVersion Include="MonoGame.Framework.DesktopGL" Version="3.8.4.1" />
    <PackageVersion Include="nkast.Kni.Platform.SDL2.GL" Version="4.2.9001.1" />
    <PackageVersion Include="nkast.Xna.Framework" Version="4.2.9001" />
    <PackageVersion Include="nkast.Xna.Framework.Audio" Version="4.2.9001" />
    <PackageVersion Include="nkast.Xna.Framework.Media" Version="4.2.9001" />
    <PackageVersion Include="PolySharp" Version="1.15.0" />
    <PackageVersion Include="SharpZipLib" Version="1.4.2" />
    <PackageVersion Include="Scriban" Version="7.2.0" />
    <PackageVersion Include="SourceGenerator.Helper.CopyCode" Version="0.0.2" />
    <PackageVersion Include="TUnit.Core" Version="1.37.36" />
    <PackageVersion Include="TUnit.Engine" Version="1.37.36" />
  </ItemGroup>
</Project>
