<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="[7.1.0]" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="17.14.2" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="1.8.2" />
    <PackageReference Include="TUnit.Core" Version="0.57.1" />
    <PackageReference Include="TUnit.Engine" Version="0.57.1" />
  </ItemGroup>

  <ItemGroup>
    <!-- Copy defs and patches folder to output. -->
    <Content Include="Content\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Define.FastCache\Define.FastCache.csproj" />
    <ProjectReference Include="..\TestSharedLib\TestSharedLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Content\ManyDefs\" />
  </ItemGroup>

</Project>
