<Project Sdk="Microsoft.NET.Sdk">

  <!-- Package info -->
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>Define.Zip</PackageId>
    <Title>Define.Zip</Title>
    <Version>1.1.0</Version>
    <AssemblyVersion>1.1.0</AssemblyVersion>
    <FileVersion>1.1.0</FileVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Define\Define.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpZipLib" />
  </ItemGroup>

</Project>
