<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>A data object parser library intended for game developers.</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <!-- Package info -->
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>Define</PackageId>
    <Title>Define</Title>
    <Version>1.1.0</Version>
    <AssemblyVersion>1.1.0</AssemblyVersion>
    <FileVersion>1.1.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="all" />
  </ItemGroup>

</Project>
