<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Content\MyImage.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" />
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Engine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Define.FastCache\Define.FastCache.csproj" />
    <ProjectReference Include="..\Define.Monogame\Define.Monogame.csproj" />
    <ProjectReference Include="..\TestSharedLib\TestSharedLib.csproj" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="mgcb /build:Content/MyImage.png" />
  </Target>

  <Import Project="..\Define.XnaSupportShared.Tests\Define.XnaSupportShared.Tests.projitems" Label="Shared" />

</Project>
