<Project Sdk="Microsoft.NET.Sdk">

  <!-- Package info -->
  <PropertyGroup>
    <PackageId>Define.KNI</PackageId>
    <Title>Define.KNI</Title>
    <Version>1.1.0</Version>
    <AssemblyVersion>1.1.0</AssemblyVersion>
    <FileVersion>1.1.0</FileVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Define\Define.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="nkast.Xna.Framework" />
    <PackageReference Include="nkast.Xna.Framework.Audio" />
    <PackageReference Include="nkast.Xna.Framework.Media" />
  </ItemGroup>

  <Import Project="..\Define.XnaSupportShared\Define.XnaSupportShared.projitems" Label="Shared" />

</Project>