<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Content\MyImage.xnb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="[7.1.0]" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="17.14.2" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="1.8.2" />
    <PackageReference Include="nkast.Kni.Platform.SDL2.GL" Version="4.1.9001.1" />
    <PackageReference Include="TUnit.Core" Version="0.57.1" />
    <PackageReference Include="TUnit.Engine" Version="0.57.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Define.FastCache\Define.FastCache.csproj" />
    <ProjectReference Include="..\Define.KNI\Define.KNI.csproj" />
    <ProjectReference Include="..\TestSharedLib\TestSharedLib.csproj" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="mgcb /build:Content/MyImage.png" />
  </Target>

  <Import Project="..\Define.XnaSupportShared.Tests\Define.XnaSupportShared.Tests.projitems" Label="Shared" />

</Project>