<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  
  <!-- Package info -->
  <PropertyGroup>
    <PackageId>Define.FastCache</PackageId>
    <Title>Define.FastCache</Title>
    <Version>1.2.0</Version>
    <AssemblyVersion>1.2.0</AssemblyVersion>
    <FileVersion>1.2.0</FileVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Ceras" />
    <PackageReference Include="JetBrains.Annotations" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Define\Define.csproj" />
  </ItemGroup>

</Project>
