name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Install mgcb
      run: dotnet tool install dotnet-mgcb --global

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Clear old packages
      run: find . -name 'Packed/*.nupkg' -delete

    - name: Pack libraries
      run: dotnet pack --configuration Release --output Packed --include-symbols --no-build --no-restore

    - name: Upload NuGet packages
      run: dotnet nuget push "Packed\*.nupkg" --api-key ${{ secrets.NUGETUPLOADAPIKEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
